[workspace]
resolver = "3"
members = ["crates/*"]
exclude = ["examples"]

[package]
name = "tauri-plugin-connectivity"
version = "0.2.0"
description = "Network connectivity monitoring plugin for Tauri applications"
license = "MIT"
edition = "2024"
rust-version = "1.94.0"
links = "tauri-plugin-connectivity"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]

[dependencies]
connectivity = { path = "crates/connectivity" }
serde = { version = "1.0.228", features = ["derive"] }
tauri = { version = "2.12.0" }
tracing = { version = "0.1.41", default-features = false, features = ["std", "log"] }

[build-dependencies]
tauri-plugin = { version = "2.7.1", features = ["build"] }
