[default]
description = "Allows querying the current network connection status and supported connection transport classes."
permissions = ["allow-connection-status", "allow-supported-connection-types"]
